#!/usr/bin/env bash
# TASK-095 Phase 4: Regenerate nginx upstream config for agent containers.
#
# Usage: ./scripts/nginx_regen.sh [--dry-run]
#
# Scans running alive-agent-* containers, extracts their host ports,
# and generates an nginx upstream config block for api.alive.kaikk.jp.
#
# Output: deploy/nginx-agents.conf (included by nginx-lounge.conf)

set -euo pipefail

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="${SCRIPT_DIR}/../deploy/nginx-agents.conf"

# Collect running agent containers and their ports
declare -A AGENTS
while IFS=$'\t' read -r name ports; do
    if [[ -z "$name" ]]; then continue; fi
    # Extract agent ID from container name
    agent_id="${name#alive-agent-}"
    # Extract host port from port mapping (e.g., "127.0.0.1:9001->8080/tcp")
    host_port=$(echo "$ports" | grep -oP '127\.0\.0\.1:\K[0-9]+' | head -1)
    if [[ -n "$host_port" ]]; then
        AGENTS["$agent_id"]="$host_port"
    fi
done < <(docker ps --filter "name=alive-agent-" --format "{{.Names}}\t{{.Ports}}" 2>/dev/null || true)

if [[ ${#AGENTS[@]} -eq 0 ]]; then
    echo "[nginx_regen] No running agent containers found."
    if [[ "$DRY_RUN" == false ]]; then
        # Write empty config
        cat > "$OUTPUT" <<'CONF'
# No agent containers running. Generated by nginx_regen.sh
CONF
        echo "[nginx_regen] Wrote empty config to ${OUTPUT}"
    fi
    exit 0
fi

echo "[nginx_regen] Found ${#AGENTS[@]} running agent(s):"

# Generate config
CONFIG="# Auto-generated by nginx_regen.sh — do not edit manually.\n"
CONFIG+="# Regenerate: ./scripts/nginx_regen.sh\n\n"

for agent_id in $(echo "${!AGENTS[@]}" | tr ' ' '\n' | sort); do
    port="${AGENTS[$agent_id]}"
    echo "  ${agent_id} → 127.0.0.1:${port}"
    CONFIG+="# Agent: ${agent_id}\n"
    CONFIG+="location /agent/${agent_id}/api/ {\n"
    CONFIG+="    proxy_pass http://127.0.0.1:${port}/api/;\n"
    CONFIG+="    proxy_set_header Host \$host;\n"
    CONFIG+="    proxy_set_header X-Real-IP \$remote_addr;\n"
    CONFIG+="    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\n"
    CONFIG+="    proxy_set_header X-Forwarded-Proto \$scheme;\n"
    CONFIG+="    proxy_read_timeout 60s;\n"
    CONFIG+="}\n\n"
done

if [[ "$DRY_RUN" == true ]]; then
    echo ""
    echo "--- Generated config (dry run) ---"
    echo -e "$CONFIG"
else
    echo -e "$CONFIG" > "$OUTPUT"
    echo "[nginx_regen] Wrote config to ${OUTPUT}"
    echo "[nginx_regen] Reload nginx: nginx -s reload"
fi
